/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Alec.Tunbridge' at '23/05/16 13:37' with Gradle 1.10
 *
 * @author Alec.Tunbridge, @date 23/05/16 13:37
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
