import java.util.ArrayList;
import java.util.List;

/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Alec.Tunbridge' at '23/05/16 13:37' with Gradle 1.10
 *
 * @author Alec.Tunbridge, @date 23/05/16 13:37
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }

    static List<Replacement> replacements = new ArrayList<>();

    static {
        replacements.add(new Replacement("CM",900));
        replacements.add(new Replacement("LM",900));
        replacements.add(new Replacement("XM",900));
        replacements.add(new Replacement("VM",900));
        replacements.add(new Replacement("IM",900));
        replacements.add(new Replacement("CM",900));
        replacements.add(new Replacement("CM",900));
        replacements.add(new Replacement("CM",900));
        replacements.add(new Replacement("CM",900));

    }


    private static class Replacement{
        String pattern;
        int iCount;

        public Replacement(String pattern, int iCount) {
            this.pattern = pattern;
            this.iCount = iCount;
        }
    }

    public String add(String paramA, String paramB) {

        StringBuilder stringBuilder = new StringBuilder();

        stringBuilder.append(expand(paramA));
        stringBuilder.append(expand(paramB));

        return squish(stringBuilder.toString());
    }

    public String squish(String s) {
        return s.replace(appendI(10), "X")
                .replace(appendI(9), "IX")
                .replace(appendI(5), "V")
                .replace(appendI(4), "IV");
    }

    public String expand(String numeral) {
        return numeral.replace("IV", appendI(4))
                .replace("IX", appendI(9))
                .replace("V", appendI(5))
                .replace("X", appendI(10));

    }

    public String appendI(int j){
        StringBuilder sb = new StringBuilder();
        for (int i=0; i<j; i++) {
            sb.append("I");
        }
        return sb.toString();
    }
}
