import org.junit.Test;

import static org.assertj.core.api.Assertions.assertThat;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'Alec.Tunbridge' at '23/05/16 13:37' with Gradle 1.10
 *
 * @author Alec.Tunbridge, @date 23/05/16 13:37
 */
public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertThat(classUnderTest.someLibraryMethod()).isTrue();
    }
}
